spring:
  application:
    name: product-service
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: us-east-1 # Change if your bucket is in a different region
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
  datasource:
    # This URL connects to your local Docker container
    url: jdbc:postgresql://localhost:5432/product_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Creates tables automatically
    show-sql: true     # Shows SQL queries in logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/